<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Product;

/**
 * ProductRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Return the list of product with all associated entities.
     *
     * @return array|null
     */
    public function findAllWhithAllEntities(): ?array
    {
        return $this->createQueryBuilder('p')
            ->leftJoin('p.pictures', 'pic')
            ->addSelect('pic')
            ->getQuery()
            ->getResult()
        ;
    }

    /**
     * Return a product with all associated entities.
     *
     * @param int $value
     *
     * @return Product|null
     */
    public function findOneWhithAllEntities(int $value): ?Product
    {
        return $this->createQueryBuilder('p')
            ->leftJoin('p.pictures', 'pic')
            ->addSelect('pic')
            ->andWhere('p.id = :id')
            ->setParameter('id', (int) $value)
            ->getQuery()
            ->getOneOrNullResult()
        ;
    }
}
