<?php

namespace AppBundle\Repository;

/**
 * ProductRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Return the list of product with all associated entities.
     *
     * @return array|null
     */
    public function findAllWhithAllEntities(): ?array
    {
        return $this->createQueryBuilder('p')
            ->leftJoin('p.pictures', 'pic')
            ->addSelect('pic')
            ->getQuery()
            ->getResult()
        ;
    }
}
